[package]
name = "tfolio"
version = "0.1.0"
description = "TFolio PDF Editor"
authors = ["Roy Tian"]
edition = "2021"

[lib]
name = "tfolio_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
